In [12]:
import pandas as pd
from sklearn.metrics import confusion_matrix, _regression
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.linear_model import LinearRegression

In [3]:
concrete_data = pd.read_csv('Concrete_Data_Yeh.csv')
concrete_data

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [4]:
x = concrete_data.drop(columns=['csMPa'])
y = concrete_data['csMPa']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [9]:
lin_model = LinearRegression()

lin_model.fit(x_train, y_train)

lin_prediction = lin_model.predict(x_test)
linmodel_accuracy = lin_model.score(x_test, y_test)

linmodel_accuracy

0.6369606518338298

In [6]:
xg_model = xgb.XGBRegressor(
                            objective='reg:squarederror',
                            n_estimators=100,
                            learning_rate=0.1,
                            max_depth=5,
                            random_state=42
                        )

xg_model.fit(x_train, y_train)

strength_prediction = xg_model.predict(x_test)
strength_accuracy = xg_model.score(x_test, y_test)

strength_accuracy

0.923878812798272